
package webservices.sei;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PizzaWebService", targetNamespace = "http://webservices/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PizzaWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.Pizza
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://webservices/", className = "webservices.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://webservices/", className = "webservices.AddResponse")
    @Action(input = "http://webservices/PizzaWebService/addRequest", output = "http://webservices/PizzaWebService/addResponse")
    public Pizza add(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
